import "../css/globals.css";
import React from "react";
import { NavBar } from "@/components/NavBar";
import classNames from "classnames";
import { HubProvider } from "@/utils/HubContext";

export const metadata = {
  title: "Github User Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames("bg-black", "px-64", "font-thin", "text-white")}
      >
        <HubProvider>
          <NavBar />
          {children}
        </HubProvider>
      </body>
    </html>
  );
}
